use crate::backend::BackendError;
use crate::host::HostInner;

// ---------------------------------------------------------------------------
// Layer 1 — Async core functions
// ---------------------------------------------------------------------------

pub async fn get_impl(inner: &HostInner, name: &str) -> Result<Option<String>, BackendError> {
    let out = inner.execute("printenv", &[name]).await?;
    if out.rc() == 0 {
        Ok(Some(out.stdout_raw().trim_end_matches('\n').to_owned()))
    } else {
        Ok(None)
    }
}

pub async fn exists_impl(inner: &HostInner, name: &str) -> Result<bool, BackendError> {
    let out = inner.execute("printenv", &[name]).await?;
    Ok(out.rc() == 0)
}

// ---------------------------------------------------------------------------
// Layers 2 + 3 — Generated by macro
// ---------------------------------------------------------------------------

oxi_nixinfra_macros::nix_module! {
    Environment {
        fields {},
        new() {},
        methods {
            fn get(name: &str) -> Option<String> => get_impl;
            fn exists(name: &str) -> bool => exists_impl;
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::mock::MockBackend;
    use crate::command::RawOutput;

    fn make_inner(responses: Vec<RawOutput>) -> HostInner {
        HostInner {
            backend: Box::new(MockBackend::new(responses)),
            runtime: tokio::runtime::Runtime::new().unwrap(),
            connection_string: "mock://".to_owned(),
        }
    }

    #[test]
    fn test_get_returns_value() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"/usr/bin:/bin\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            inner.runtime.block_on(get_impl(&inner, "PATH")).unwrap(),
            Some("/usr/bin:/bin".to_owned())
        );
    }

    #[test]
    fn test_get_returns_none_for_unset() {
        let inner = make_inner(vec![RawOutput {
            rc: 1,
            stdout: vec![],
            stderr: vec![],
        }]);
        assert_eq!(
            inner
                .runtime
                .block_on(get_impl(&inner, "NONEXISTENT_VAR"))
                .unwrap(),
            None
        );
    }

    #[test]
    fn test_exists_true() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"/home/user\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(inner.runtime.block_on(exists_impl(&inner, "HOME")).unwrap());
    }

    #[test]
    fn test_exists_false() {
        let inner = make_inner(vec![RawOutput {
            rc: 1,
            stdout: vec![],
            stderr: vec![],
        }]);
        assert!(
            !inner
                .runtime
                .block_on(exists_impl(&inner, "NONEXISTENT_VAR"))
                .unwrap()
        );
    }
}
