use crate::backend::BackendError;
use crate::host::HostInner;

// ---------------------------------------------------------------------------
// Layer 1 — Async core functions
// ---------------------------------------------------------------------------

pub async fn get_impl(inner: &HostInner, name: &str) -> Result<Option<String>, BackendError> {
    let out = inner.execute("printenv", &[name]).await?;
    if out.rc() == 0 {
        Ok(Some(out.stdout_raw().trim_end_matches('\n').to_owned()))
    } else {
        Ok(None)
    }
}

pub async fn exists_impl(inner: &HostInner, name: &str) -> Result<bool, BackendError> {
    let out = inner.execute("printenv", &[name]).await?;
    Ok(out.rc() == 0)
}

// ---------------------------------------------------------------------------
// Layers 2 + 3 — Generated by macro
// ---------------------------------------------------------------------------

oxi_nixinfra_macros::nix_module! {
    Environment {
        fields {},
        new() {},
        methods {
            fn get(name: &str) -> Option<String> => get_impl;
            fn exists(name: &str) -> bool => exists_impl;
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::mock::TestHarness;
    use crate::command::RawOutput;

    #[test]
    fn test_get_returns_value() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"/usr/bin:/bin\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            h.inner
                .runtime
                .block_on(get_impl(&h.inner, "PATH"))
                .unwrap(),
            Some("/usr/bin:/bin".to_owned())
        );
        assert_eq!(h.calls(), [("printenv".into(), vec!["PATH".into()])]);
    }

    #[test]
    fn test_get_returns_none_for_unset() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 1,
            stdout: vec![],
            stderr: vec![],
        }]);
        assert_eq!(
            h.inner
                .runtime
                .block_on(get_impl(&h.inner, "NONEXISTENT_VAR"))
                .unwrap(),
            None
        );
    }

    #[test]
    fn test_exists_true() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"/home/user\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            h.inner
                .runtime
                .block_on(exists_impl(&h.inner, "HOME"))
                .unwrap()
        );
        assert_eq!(h.calls(), [("printenv".into(), vec!["HOME".into()])]);
    }

    #[test]
    fn test_exists_false() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 1,
            stdout: vec![],
            stderr: vec![],
        }]);
        assert!(
            !h.inner
                .runtime
                .block_on(exists_impl(&h.inner, "NONEXISTENT_VAR"))
                .unwrap()
        );
    }
}
