use crate::backend::BackendError;
use crate::host::HostInner;

// ---------------------------------------------------------------------------
// Layer 1 — Async core functions
// ---------------------------------------------------------------------------

pub async fn exists_impl(inner: &HostInner, path: &str) -> Result<bool, BackendError> {
    let out = inner.execute("test", &["-e", path]).await?;
    Ok(out.rc() == 0)
}

pub async fn is_file_impl(inner: &HostInner, path: &str) -> Result<bool, BackendError> {
    let out = inner.execute("test", &["-f", path]).await?;
    Ok(out.rc() == 0)
}

pub async fn is_directory_impl(inner: &HostInner, path: &str) -> Result<bool, BackendError> {
    let out = inner.execute("test", &["-d", path]).await?;
    Ok(out.rc() == 0)
}

pub async fn is_symlink_impl(inner: &HostInner, path: &str) -> Result<bool, BackendError> {
    let out = inner.execute("test", &["-L", path]).await?;
    Ok(out.rc() == 0)
}

pub async fn is_executable_impl(inner: &HostInner, path: &str) -> Result<bool, BackendError> {
    let out = inner.execute("test", &["-x", path]).await?;
    Ok(out.rc() == 0)
}

pub async fn is_pipe_impl(inner: &HostInner, path: &str) -> Result<bool, BackendError> {
    let out = inner.execute("test", &["-p", path]).await?;
    Ok(out.rc() == 0)
}

pub async fn is_socket_impl(inner: &HostInner, path: &str) -> Result<bool, BackendError> {
    let out = inner.execute("test", &["-S", path]).await?;
    Ok(out.rc() == 0)
}

pub async fn linked_to_impl(inner: &HostInner, path: &str) -> Result<String, BackendError> {
    let out = inner.execute("realpath", &[path]).await?;
    Ok(out.stdout().to_owned())
}

pub async fn user_impl(inner: &HostInner, path: &str) -> Result<String, BackendError> {
    let out = inner.execute("stat", &["-Lc", "%U", path]).await?;
    Ok(out.stdout().to_owned())
}

pub async fn uid_impl(inner: &HostInner, path: &str) -> Result<i32, BackendError> {
    let out = inner.execute("stat", &["-Lc", "%u", path]).await?;
    out.parse_int("uid")
}

pub async fn group_impl(inner: &HostInner, path: &str) -> Result<String, BackendError> {
    let out = inner.execute("stat", &["-Lc", "%G", path]).await?;
    Ok(out.stdout().to_owned())
}

pub async fn gid_impl(inner: &HostInner, path: &str) -> Result<i32, BackendError> {
    let out = inner.execute("stat", &["-Lc", "%g", path]).await?;
    out.parse_int("gid")
}

pub async fn mode_impl(inner: &HostInner, path: &str) -> Result<i32, BackendError> {
    let out = inner.execute("stat", &["-Lc", "%a", path]).await?;
    out.parse_int_radix("mode", 8)
}

pub async fn size_impl(inner: &HostInner, path: &str) -> Result<u64, BackendError> {
    let out = inner.execute("stat", &["-Lc", "%s", path]).await?;
    out.parse_int("size")
}

pub async fn content_impl(inner: &HostInner, path: &str) -> Result<String, BackendError> {
    let out = inner.execute("cat", &["--", path]).await?;
    Ok(out.stdout_raw())
}

pub async fn contains_impl(
    inner: &HostInner,
    path: &str,
    pattern: &str,
) -> Result<bool, BackendError> {
    let out = inner.execute("grep", &["-qs", "--", pattern, path]).await?;
    Ok(out.rc() == 0)
}

pub async fn is_nix_managed_impl(inner: &HostInner, path: &str) -> Result<bool, BackendError> {
    let out = inner.execute("readlink", &["-f", path]).await?;
    Ok(out.rc() == 0 && out.stdout().starts_with("/nix/store/"))
}

pub async fn file_store_path_impl(
    inner: &HostInner,
    path: &str,
) -> Result<Option<String>, BackendError> {
    let out = inner.execute("readlink", &["-f", path]).await?;
    let resolved = out.stdout();
    if out.rc() == 0 && resolved.starts_with("/nix/store/") {
        Ok(Some(resolved.to_owned()))
    } else {
        Ok(None)
    }
}

pub async fn md5sum_impl(inner: &HostInner, path: &str) -> Result<String, BackendError> {
    let out = inner.execute("md5sum", &[path]).await?;
    out.first_field("md5sum").map(ToOwned::to_owned)
}

pub async fn sha256sum_impl(inner: &HostInner, path: &str) -> Result<String, BackendError> {
    let out = inner.execute("sha256sum", &[path]).await?;
    out.first_field("sha256sum").map(ToOwned::to_owned)
}

pub async fn listdir_impl(inner: &HostInner, path: &str) -> Result<Vec<String>, BackendError> {
    let out = inner.execute("ls", &["-1", "-q", "--", path]).await?;
    Ok(out.lines().map(ToOwned::to_owned).collect())
}

// ---------------------------------------------------------------------------
// Layers 2 + 3 — Generated by macro
// ---------------------------------------------------------------------------

oxi_nixinfra_macros::nix_module! {
    File {
        fields { path: String },
        new(path: &str) {
            path: path.to_owned(),
        },
        methods {
            fn exists() -> bool => exists_impl;
            fn is_file() -> bool => is_file_impl;
            fn is_directory() -> bool => is_directory_impl;
            fn is_symlink() -> bool => is_symlink_impl;
            fn is_executable() -> bool => is_executable_impl;
            fn is_pipe() -> bool => is_pipe_impl;
            fn is_socket() -> bool => is_socket_impl;
            fn linked_to() -> String => linked_to_impl;
            fn user() -> String => user_impl;
            fn uid() -> i32 => uid_impl;
            fn group() -> String => group_impl;
            fn gid() -> i32 => gid_impl;
            fn mode() -> i32 => mode_impl;
            fn size() -> u64 => size_impl;
            fn content() -> String => content_impl;
            fn contains(pattern: &str) -> bool => contains_impl;
            fn md5sum() -> String => md5sum_impl;
            fn sha256sum() -> String => sha256sum_impl;
            fn listdir() -> Vec<String> => listdir_impl;
            fn is_nix_managed() -> bool => is_nix_managed_impl;
            fn store_path() -> Option<String> => file_store_path_impl;
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::mock::MockBackend;
    use crate::command::RawOutput;

    fn make_inner(responses: Vec<RawOutput>) -> HostInner {
        HostInner {
            backend: Box::new(MockBackend::new(responses)),
            runtime: tokio::runtime::Runtime::new().unwrap(),
            connection_string: "mock://".to_owned(),
        }
    }

    #[test]
    fn test_mode_octal_parse() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"644\n".to_vec(),
            stderr: vec![],
        }]);
        let mode = inner
            .runtime
            .block_on(mode_impl(&inner, "/etc/passwd"))
            .unwrap();
        assert_eq!(mode, 0o644);
    }

    #[test]
    fn test_md5sum_split_field() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"d41d8cd98f00b204e9800998ecf8427e  /dev/null\n".to_vec(),
            stderr: vec![],
        }]);
        let hash = inner
            .runtime
            .block_on(md5sum_impl(&inner, "/dev/null"))
            .unwrap();
        assert_eq!(hash, "d41d8cd98f00b204e9800998ecf8427e");
    }

    #[test]
    fn test_uid_parse_int() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"1000\n".to_vec(),
            stderr: vec![],
        }]);
        let uid = inner
            .runtime
            .block_on(uid_impl(&inner, "/home/user"))
            .unwrap();
        assert_eq!(uid, 1000);
    }

    #[test]
    fn test_contains_found() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: vec![],
            stderr: vec![],
        }]);
        assert!(
            inner
                .runtime
                .block_on(contains_impl(&inner, "/etc/hosts", "localhost"))
                .unwrap()
        );
    }

    #[test]
    fn test_contains_not_found() {
        let inner = make_inner(vec![RawOutput {
            rc: 1,
            stdout: vec![],
            stderr: vec![],
        }]);
        assert!(
            !inner
                .runtime
                .block_on(contains_impl(&inner, "/etc/hosts", "nonexistent"))
                .unwrap()
        );
    }

    #[test]
    fn test_is_nix_managed_true() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"/nix/store/h0p1rl4srn0j3arkiahpwrv8fp8vpp8l-hosts\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            inner
                .runtime
                .block_on(is_nix_managed_impl(&inner, "/etc/hosts"))
                .unwrap()
        );
    }

    #[test]
    fn test_is_nix_managed_false() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"/etc/resolv.conf\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            !inner
                .runtime
                .block_on(is_nix_managed_impl(&inner, "/etc/resolv.conf"))
                .unwrap()
        );
    }

    #[test]
    fn test_file_store_path_some() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"/nix/store/x1nwcwf197wb5d7infxr4il5l4gzpdp3-nix.conf\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            inner
                .runtime
                .block_on(file_store_path_impl(&inner, "/etc/nix/nix.conf"))
                .unwrap(),
            Some("/nix/store/x1nwcwf197wb5d7infxr4il5l4gzpdp3-nix.conf".to_owned())
        );
    }

    #[test]
    fn test_file_store_path_none() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"/etc/passwd\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            inner
                .runtime
                .block_on(file_store_path_impl(&inner, "/etc/passwd"))
                .unwrap(),
            None
        );
    }

    #[test]
    fn test_listdir_parse() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"file1.txt\nfile2.txt\ndir1\n".to_vec(),
            stderr: vec![],
        }]);
        let entries = inner
            .runtime
            .block_on(listdir_impl(&inner, "/tmp"))
            .unwrap();
        assert_eq!(entries, vec!["file1.txt", "file2.txt", "dir1"]);
    }
}
