use crate::backend::BackendError;
use crate::host::HostInner;

// ---------------------------------------------------------------------------
// Layer 1 — Async core functions
// ---------------------------------------------------------------------------

pub async fn exists_impl(inner: &HostInner, path: &str) -> Result<bool, BackendError> {
    let out = inner
        .execute("findmnt", &["--json", "--target", path])
        .await?;
    Ok(out.rc() == 0)
}

async fn findmnt_field(inner: &HostInner, path: &str, field: &str) -> Result<String, BackendError> {
    let out = inner
        .execute("findmnt", &["--json", "--target", path])
        .await?;
    if out.rc() != 0 {
        return Err(BackendError::Execution(format!(
            "findmnt failed for '{path}': {}",
            out.stderr_lossy()
        )));
    }
    out.json_field(field)
        .map_err(|_| BackendError::Execution(format!("could not parse {field} for mount: {path}")))
}

pub async fn filesystem_impl(inner: &HostInner, path: &str) -> Result<String, BackendError> {
    findmnt_field(inner, path, "fstype").await
}

pub async fn device_impl(inner: &HostInner, path: &str) -> Result<String, BackendError> {
    findmnt_field(inner, path, "source").await
}

pub async fn options_impl(inner: &HostInner, path: &str) -> Result<Vec<String>, BackendError> {
    let opts = findmnt_field(inner, path, "options").await?;
    Ok(opts
        .split(',')
        .map(std::borrow::ToOwned::to_owned)
        .collect())
}

// ---------------------------------------------------------------------------
// Layers 2 + 3 — Generated by macro
// ---------------------------------------------------------------------------

oxi_nixinfra_macros::nix_module! {
    MountPoint {
        fields { path: String },
        new(path: &str) {
            path: path.to_owned(),
        },
        methods {
            fn exists() -> bool => exists_impl;
            fn filesystem() -> String => filesystem_impl;
            fn device() -> String => device_impl;
            fn options() -> Vec<String> => options_impl;
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::mock::MockBackend;
    use crate::command::RawOutput;

    fn make_inner(responses: Vec<RawOutput>) -> HostInner {
        HostInner {
            backend: Box::new(MockBackend::new(responses)),
            runtime: tokio::runtime::Runtime::new().unwrap(),
            connection_string: "mock://".to_owned(),
        }
    }

    const FINDMNT_JSON: &[u8] = br#"{"filesystems": [{"target":"/","source":"/dev/sda1","fstype":"ext4","options":"rw,relatime"}]}"#;

    #[test]
    fn test_exists_true() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: FINDMNT_JSON.to_vec(),
            stderr: vec![],
        }]);
        assert!(inner.runtime.block_on(exists_impl(&inner, "/")).unwrap());
    }

    #[test]
    fn test_exists_false() {
        let inner = make_inner(vec![RawOutput {
            rc: 1,
            stdout: vec![],
            stderr: vec![],
        }]);
        assert!(
            !inner
                .runtime
                .block_on(exists_impl(&inner, "/nonexistent"))
                .unwrap()
        );
    }

    #[test]
    fn test_filesystem() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: FINDMNT_JSON.to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            inner
                .runtime
                .block_on(filesystem_impl(&inner, "/"))
                .unwrap(),
            "ext4"
        );
    }

    #[test]
    fn test_device() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: FINDMNT_JSON.to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            inner.runtime.block_on(device_impl(&inner, "/")).unwrap(),
            "/dev/sda1"
        );
    }

    #[test]
    fn test_options() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: FINDMNT_JSON.to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            inner.runtime.block_on(options_impl(&inner, "/")).unwrap(),
            vec!["rw", "relatime"]
        );
    }

    #[test]
    fn test_filesystem_error_on_not_found() {
        let inner = make_inner(vec![RawOutput {
            rc: 1,
            stdout: vec![],
            stderr: b"findmnt: target not found\n".to_vec(),
        }]);
        let err = inner
            .runtime
            .block_on(filesystem_impl(&inner, "/nonexistent"))
            .unwrap_err();
        assert!(err.to_string().contains("findmnt failed"));
    }
}
