use crate::backend::BackendError;
use crate::host::HostInner;

// ---------------------------------------------------------------------------
// Layer 1 — Async core functions
// ---------------------------------------------------------------------------

async fn find_store_path(inner: &HostInner, name: &str) -> Result<Option<String>, BackendError> {
    let out = inner
        .execute(
            "nix-store",
            &["-q", "--references", "/run/current-system/sw"],
        )
        .await?;
    let stdout = String::from_utf8_lossy(&out.stdout);
    Ok(stdout
        .lines()
        .find(|line| line.contains(name))
        .map(std::borrow::ToOwned::to_owned))
}

pub fn parse_version_from_store_path(store_path: &str, name: &str) -> Option<String> {
    let basename = store_path.rsplit('/').next()?;
    let after_hash = basename.get(33..)?;
    let name_pos = after_hash.find(name)?;
    let after_name = &after_hash[name_pos + name.len()..];
    after_name
        .strip_prefix('-')
        .map(std::borrow::ToOwned::to_owned)
}

pub async fn is_installed_impl(inner: &HostInner, name: &str) -> Result<bool, BackendError> {
    Ok(find_store_path(inner, name).await?.is_some())
}

pub async fn version_impl(inner: &HostInner, name: &str) -> Result<Option<String>, BackendError> {
    let path = find_store_path(inner, name).await?;
    Ok(path.and_then(|p| parse_version_from_store_path(&p, name)))
}

pub async fn store_path_impl(
    inner: &HostInner,
    name: &str,
) -> Result<Option<String>, BackendError> {
    find_store_path(inner, name).await
}

// ---------------------------------------------------------------------------
// Layers 2 + 3 — Generated by macro
// ---------------------------------------------------------------------------

oxi_nixinfra_macros::nix_module! {
    NixPackage {
        fields { name: String },
        new(name: &str) {
            name: name.to_owned(),
        },
        methods {
            fn is_installed() -> bool => is_installed_impl;
            fn version() -> Option<String> => version_impl;
            fn store_path() -> Option<String> => store_path_impl;
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_version_simple() {
        let path = "/nix/store/abc123abc123abc123abc123abc123ab-git-2.44.0";
        assert_eq!(
            parse_version_from_store_path(path, "git"),
            Some("2.44.0".to_owned())
        );
    }

    #[test]
    fn test_parse_version_hyphenated_name() {
        let path = "/nix/store/abc123abc123abc123abc123abc123ab-nix-output-monitor-2.1.2";
        assert_eq!(
            parse_version_from_store_path(path, "nix-output-monitor"),
            Some("2.1.2".to_owned())
        );
    }

    #[test]
    fn test_parse_version_no_match() {
        let path = "/nix/store/abc123abc123abc123abc123abc123ab-git-2.44.0";
        assert_eq!(parse_version_from_store_path(path, "vim"), None);
    }

    #[test]
    fn test_parse_version_no_version_suffix() {
        let path = "/nix/store/abc123abc123abc123abc123abc123ab-env-manifest.nix";
        assert_eq!(
            parse_version_from_store_path(path, "env-manifest.nix"),
            None
        );
    }

    #[test]
    fn test_is_installed_found() {
        use crate::backend::mock::MockBackend;
        use crate::command::RawOutput;

        let inner = HostInner {
            backend: Box::new(MockBackend::new(vec![RawOutput {
                rc: 0,
                stdout: b"/nix/store/abc123abc123abc123abc123abc123ab-git-2.44.0\n\
                          /nix/store/def456def456def456def456def456de-vim-9.1\n"
                    .to_vec(),
                stderr: vec![],
            }])),
            runtime: tokio::runtime::Runtime::new().unwrap(),
            connection_string: "mock://".to_owned(),
        };
        assert!(
            inner
                .runtime
                .block_on(is_installed_impl(&inner, "git"))
                .unwrap()
        );
    }

    #[test]
    fn test_is_installed_not_found() {
        use crate::backend::mock::MockBackend;
        use crate::command::RawOutput;

        let inner = HostInner {
            backend: Box::new(MockBackend::new(vec![RawOutput {
                rc: 0,
                stdout: b"/nix/store/abc123abc123abc123abc123abc123ab-git-2.44.0\n".to_vec(),
                stderr: vec![],
            }])),
            runtime: tokio::runtime::Runtime::new().unwrap(),
            connection_string: "mock://".to_owned(),
        };
        assert!(
            !inner
                .runtime
                .block_on(is_installed_impl(&inner, "emacs"))
                .unwrap()
        );
    }
}
