use crate::backend::BackendError;
use crate::host::HostInner;

// ---------------------------------------------------------------------------
// Layer 1 — Async core functions (unchanged)
// ---------------------------------------------------------------------------

/// Check if a NixOS option exists at the given path.
///
/// **Local-only**: Uses `nixos-option` which evaluates the full Nix expression
/// tree. This requires access to the system's Nix configuration source and
/// does not work on remote hosts via SSH.
pub async fn exists_impl(inner: &HostInner, path: &str) -> Result<bool, BackendError> {
    let out = inner.execute("nixos-option", &[path]).await?;
    Ok(out.rc() == 0)
}

/// Get the value of a NixOS option at the given path.
///
/// **Local-only**: Uses `nixos-option` which evaluates the full Nix expression
/// tree. This requires access to the system's Nix configuration source and
/// does not work on remote hosts via SSH.
pub async fn value_impl(inner: &HostInner, path: &str) -> Result<String, BackendError> {
    let out = inner.execute("nixos-option", &[path]).await?;
    if out.rc() == 0 {
        let lines: Vec<&str> = out.lines().collect();
        for (i, line) in lines.iter().enumerate() {
            if line.starts_with("Value:") {
                return lines[i + 1..]
                    .iter()
                    .find(|l| !l.trim().is_empty())
                    .map(|l| l.trim().to_owned())
                    .ok_or_else(|| {
                        BackendError::Execution(format!("could not parse value for: {path}"))
                    });
            }
        }
    }
    Err(BackendError::Execution(format!(
        "nixos-option failed for '{}': {}",
        path,
        out.stderr_lossy()
    )))
}

// ---------------------------------------------------------------------------
// Layers 2 + 3 — Generated by macro
// ---------------------------------------------------------------------------

oxi_nixinfra_macros::nix_module! {
    NixOption {
        fields { path: String },
        new(path: &str) {
            path: path.to_owned(),
        },
        methods {
            fn exists() -> bool => exists_impl;
            fn value() -> String => value_impl;
        }
    }
}

// ---------------------------------------------------------------------------
// Tests (unchanged)
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::mock::MockBackend;
    use crate::command::RawOutput;

    fn make_inner(responses: Vec<RawOutput>) -> HostInner {
        HostInner {
            backend: Box::new(MockBackend::new(responses)),
            runtime: tokio::runtime::Runtime::new().unwrap(),
            connection_string: "mock://".to_owned(),
        }
    }

    #[test]
    fn test_exists_true() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"Value:\n  true\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            inner
                .runtime
                .block_on(exists_impl(&inner, "services.openssh.enable"))
                .unwrap()
        );
    }

    #[test]
    fn test_exists_false() {
        let inner = make_inner(vec![RawOutput {
            rc: 1,
            stdout: vec![],
            stderr: b"error: option not found\n".to_vec(),
        }]);
        assert!(
            !inner
                .runtime
                .block_on(exists_impl(&inner, "services.nonexistent"))
                .unwrap()
        );
    }

    #[test]
    fn test_value_parse() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"Value:\n  true\n\nDefault:\n  false\n".to_vec(),
            stderr: vec![],
        }]);
        let val = inner
            .runtime
            .block_on(value_impl(&inner, "services.openssh.enable"))
            .unwrap();
        assert_eq!(val, "true");
    }

    #[test]
    fn test_value_error_on_failure() {
        let inner = make_inner(vec![RawOutput {
            rc: 1,
            stdout: vec![],
            stderr: b"error: option not found\n".to_vec(),
        }]);
        let err = inner
            .runtime
            .block_on(value_impl(&inner, "nonexistent.option"))
            .unwrap_err();
        assert!(err.to_string().contains("nixos-option failed"));
    }
}
