use std::collections::HashMap;

use crate::backend::BackendError;
use crate::host::HostInner;

// ---------------------------------------------------------------------------
// Layer 1 — Async core functions
// ---------------------------------------------------------------------------

fn parse_ps_line(line: &str) -> Option<HashMap<String, String>> {
    let trimmed = line.trim();
    if trimmed.is_empty() {
        return None;
    }
    // Use split_ascii_whitespace (collapses runs) for pid/user/comm, then
    // capture the rest of the original string as args.
    let mut ws = trimmed.splitn(2, char::is_whitespace);
    let pid = ws.next()?.trim().to_owned();
    let rest1 = ws.next()?.trim_start();

    let mut ws = rest1.splitn(2, char::is_whitespace);
    let user = ws.next()?.trim().to_owned();
    let rest2 = ws.next()?.trim_start();

    let mut ws = rest2.splitn(2, char::is_whitespace);
    let comm = ws.next()?.trim().to_owned();
    let args = ws.next().unwrap_or("").trim().to_owned();

    Some(HashMap::from([
        ("pid".to_owned(), pid),
        ("user".to_owned(), user),
        ("comm".to_owned(), comm),
        ("args".to_owned(), args),
    ]))
}

pub async fn list_impl(inner: &HostInner) -> Result<Vec<HashMap<String, String>>, BackendError> {
    let out = inner
        .execute("ps", &["-eo", "pid,user,comm,args", "--no-headers"])
        .await?;
    Ok(out.lines().filter_map(parse_ps_line).collect())
}

pub async fn filter_impl(
    inner: &HostInner,
    user: Option<&str>,
    comm: Option<&str>,
) -> Result<Vec<HashMap<String, String>>, BackendError> {
    let procs = list_impl(inner).await?;
    Ok(procs
        .into_iter()
        .filter(|p| {
            user.is_none_or(|u| p.get("user").is_some_and(|v| v == u))
                && comm.is_none_or(|c| p.get("comm").is_some_and(|v| v == c))
        })
        .collect())
}

pub async fn exists_impl(inner: &HostInner, comm: &str) -> Result<bool, BackendError> {
    let out = inner
        .execute("ps", &["-eo", "comm", "--no-headers"])
        .await?;
    Ok(out.lines().any(|line| line.trim() == comm))
}

pub async fn pids_impl(inner: &HostInner, comm: &str) -> Result<Vec<i32>, BackendError> {
    let out = inner
        .execute("ps", &["-eo", "pid,comm", "--no-headers"])
        .await?;
    Ok(out
        .lines()
        .filter_map(|line| {
            let mut parts = line.trim().splitn(2, char::is_whitespace);
            let pid = parts.next()?.trim();
            let name = parts.next()?.trim();
            if name == comm {
                pid.parse::<i32>().ok()
            } else {
                None
            }
        })
        .collect())
}

pub async fn count_impl(inner: &HostInner, comm: &str) -> Result<i32, BackendError> {
    let out = inner
        .execute("ps", &["-eo", "comm", "--no-headers"])
        .await?;
    #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
    let count = out.lines().filter(|line| line.trim() == comm).count() as i32;
    Ok(count)
}

// ---------------------------------------------------------------------------
// Layers 2 + 3 — Generated by macro
// ---------------------------------------------------------------------------

oxi_nixinfra_macros::nix_module! {
    Process {
        fields {},
        new() {},
        methods {
            fn list() -> Vec<HashMap<String, String>> => list_impl;
            fn exists(comm: &str) -> bool => exists_impl;
            fn pids(comm: &str) -> Vec<i32> => pids_impl;
            fn count(comm: &str) -> i32 => count_impl;
        }
    }
}

// Manual method: filter has optional kwargs
#[pyo3::prelude::pymethods]
impl Process {
    #[pyo3(signature = (user = None, comm = None))]
    fn filter(
        &self,
        user: Option<&str>,
        comm: Option<&str>,
    ) -> pyo3::prelude::PyResult<Vec<HashMap<String, String>>> {
        crate::helpers::wrap_sync(&self.inner, filter_impl(&self.inner, user, comm))
    }
}

#[pyo3::prelude::pymethods]
impl AsyncProcess {
    #[pyo3(signature = (user = None, comm = None))]
    fn filter<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
        user: Option<String>,
        comm: Option<String>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            filter_impl(&inner, user.as_deref(), comm.as_deref())
                .await
                .map_err(crate::helpers::backend_err_to_py)
        })
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::mock::MockBackend;
    use crate::command::RawOutput;

    fn make_inner(responses: Vec<RawOutput>) -> HostInner {
        HostInner {
            backend: Box::new(MockBackend::new(responses)),
            runtime: tokio::runtime::Runtime::new().unwrap(),
            connection_string: "mock://".to_owned(),
        }
    }

    const PS_OUTPUT: &[u8] = b"    1 root     systemd         /sbin/init\n  123 root     sshd            /usr/sbin/sshd -D\n  456 nobody   nginx           nginx: master process\n";

    #[test]
    fn test_parse_ps_line() {
        let line = "    1 root     systemd         /sbin/init";
        let entry = parse_ps_line(line).unwrap();
        assert_eq!(entry.get("pid").unwrap(), "1");
        assert_eq!(entry.get("user").unwrap(), "root");
        assert_eq!(entry.get("comm").unwrap(), "systemd");
        assert_eq!(entry.get("args").unwrap(), "/sbin/init");
    }

    #[test]
    fn test_parse_ps_line_empty() {
        assert!(parse_ps_line("").is_none());
        assert!(parse_ps_line("   ").is_none());
    }

    #[test]
    fn test_list() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: PS_OUTPUT.to_vec(),
            stderr: vec![],
        }]);
        let procs = inner.runtime.block_on(list_impl(&inner)).unwrap();
        assert_eq!(procs.len(), 3);
        assert_eq!(procs[0].get("comm").unwrap(), "systemd");
        assert_eq!(procs[2].get("user").unwrap(), "nobody");
    }

    #[test]
    fn test_filter_by_user() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: PS_OUTPUT.to_vec(),
            stderr: vec![],
        }]);
        let procs = inner
            .runtime
            .block_on(filter_impl(&inner, Some("root"), None))
            .unwrap();
        assert_eq!(procs.len(), 2);
    }

    #[test]
    fn test_filter_by_comm() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: PS_OUTPUT.to_vec(),
            stderr: vec![],
        }]);
        let procs = inner
            .runtime
            .block_on(filter_impl(&inner, None, Some("nginx")))
            .unwrap();
        assert_eq!(procs.len(), 1);
        assert_eq!(procs[0].get("user").unwrap(), "nobody");
    }

    #[test]
    fn test_filter_by_both() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: PS_OUTPUT.to_vec(),
            stderr: vec![],
        }]);
        let procs = inner
            .runtime
            .block_on(filter_impl(&inner, Some("root"), Some("sshd")))
            .unwrap();
        assert_eq!(procs.len(), 1);
    }

    #[test]
    fn test_filter_no_match() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: PS_OUTPUT.to_vec(),
            stderr: vec![],
        }]);
        let procs = inner
            .runtime
            .block_on(filter_impl(&inner, Some("nobody"), Some("sshd")))
            .unwrap();
        assert!(procs.is_empty());
    }

    #[test]
    fn test_exists_true() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"systemd\nsshd\nnginx\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(inner.runtime.block_on(exists_impl(&inner, "sshd")).unwrap());
    }

    #[test]
    fn test_exists_false() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"systemd\nsshd\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            !inner
                .runtime
                .block_on(exists_impl(&inner, "nginx"))
                .unwrap()
        );
    }

    #[test]
    fn test_pids() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"    1 systemd\n  123 sshd\n  456 sshd\n  789 nginx\n".to_vec(),
            stderr: vec![],
        }]);
        let pids = inner.runtime.block_on(pids_impl(&inner, "sshd")).unwrap();
        assert_eq!(pids, vec![123, 456]);
    }

    #[test]
    fn test_count() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"systemd\nsshd\nsshd\nnginx\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            inner.runtime.block_on(count_impl(&inner, "sshd")).unwrap(),
            2
        );
    }
}
