use std::collections::HashMap;

use crate::backend::BackendError;
use crate::host::HostInner;

// ---------------------------------------------------------------------------
// Layer 1 — Async core functions
// ---------------------------------------------------------------------------

pub async fn is_running_impl(inner: &HostInner, name: &str) -> Result<bool, BackendError> {
    let out = inner.execute("systemctl", &["is-active", name]).await?;
    Ok(out.rc() == 0)
}

pub async fn is_managed_impl(inner: &HostInner, name: &str) -> Result<bool, BackendError> {
    let path = format!("/etc/systemd/system/{name}.service");
    let out = inner.execute("readlink", &["-f", &path]).await?;
    Ok(out.rc() == 0 && out.stdout().starts_with("/nix/store/"))
}

pub async fn store_path_impl(
    inner: &HostInner,
    name: &str,
) -> Result<Option<String>, BackendError> {
    let path = format!("/etc/systemd/system/{name}.service");
    let out = inner.execute("readlink", &["-f", &path]).await?;
    let resolved = out.stdout();
    if out.rc() == 0 && resolved.starts_with("/nix/store/") {
        Ok(Some(resolved.to_owned()))
    } else {
        Ok(None)
    }
}

pub async fn enablement_status_impl(inner: &HostInner, name: &str) -> Result<String, BackendError> {
    let out = inner
        .execute(
            "systemctl",
            &["show", name, "-p", "UnitFileState", "--value"],
        )
        .await?;
    Ok(out.stdout().to_owned())
}

pub async fn exists_impl(inner: &HostInner, name: &str) -> Result<bool, BackendError> {
    let out = inner
        .execute("systemctl", &["list-unit-files", "--no-pager"])
        .await?;
    Ok(out.lines().any(|line| line.starts_with(name)))
}

pub async fn is_valid_impl(inner: &HostInner, name: &str) -> Result<bool, BackendError> {
    let unit = if name.contains('.') {
        name.to_owned()
    } else {
        format!("{name}.service")
    };
    let out = inner.execute("systemd-analyze", &["verify", &unit]).await?;
    Ok(out.stdout_bytes().is_empty() && out.stderr_bytes().is_empty())
}

pub async fn properties_impl(
    inner: &HostInner,
    name: &str,
) -> Result<HashMap<String, String>, BackendError> {
    let out = inner.execute("systemctl", &["show", name]).await?;
    Ok(out.kv_pairs('='))
}

// ---------------------------------------------------------------------------
// Layers 2 + 3 — Generated by macro
// ---------------------------------------------------------------------------

oxi_nixinfra_macros::nix_module! {
    Service {
        fields { name: String },
        new(name: &str) {
            name: name.to_owned(),
        },
        methods {
            fn is_running() -> bool => is_running_impl;
            fn is_managed() -> bool => is_managed_impl;
            fn enablement_status() -> String => enablement_status_impl;
            fn store_path() -> Option<String> => store_path_impl;
            fn exists() -> bool => exists_impl;
            fn is_valid() -> bool => is_valid_impl;
            fn properties() -> HashMap<String, String> => properties_impl;
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::mock::TestHarness;
    use crate::command::RawOutput;

    #[test]
    fn test_is_running_active() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"active\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            h.inner
                .runtime
                .block_on(is_running_impl(&h.inner, "nix-daemon"))
                .unwrap()
        );
        assert_eq!(
            h.calls(),
            [(
                "systemctl".into(),
                vec!["is-active".into(), "nix-daemon".into()]
            )]
        );
    }

    #[test]
    fn test_is_running_inactive() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 3,
            stdout: b"inactive\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            !h.inner
                .runtime
                .block_on(is_running_impl(&h.inner, "nix-daemon"))
                .unwrap()
        );
    }

    #[test]
    fn test_is_managed_nix_store_path() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"/nix/store/abc123-nix-2.31.4/lib/systemd/system/nix-daemon.service\n"
                .to_vec(),
            stderr: vec![],
        }]);
        assert!(
            h.inner
                .runtime
                .block_on(is_managed_impl(&h.inner, "nix-daemon"))
                .unwrap()
        );
        assert_eq!(
            h.calls(),
            [(
                "readlink".into(),
                vec!["-f".into(), "/etc/systemd/system/nix-daemon.service".into()]
            )]
        );
    }

    #[test]
    fn test_is_managed_dev_null() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"/dev/null\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            !h.inner
                .runtime
                .block_on(is_managed_impl(&h.inner, "console-getty"))
                .unwrap()
        );
    }

    #[test]
    fn test_is_managed_not_found() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 1,
            stdout: b"".to_vec(),
            stderr: b"readlink: /etc/systemd/system/sshd.service: No such file or directory\n"
                .to_vec(),
        }]);
        assert!(
            !h.inner
                .runtime
                .block_on(is_managed_impl(&h.inner, "sshd"))
                .unwrap()
        );
    }

    #[test]
    fn test_store_path_returns_path() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"/nix/store/abc123-nix-2.31.4/lib/systemd/system/nix-daemon.service\n"
                .to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            h.inner
                .runtime
                .block_on(store_path_impl(&h.inner, "nix-daemon"))
                .unwrap(),
            Some("/nix/store/abc123-nix-2.31.4/lib/systemd/system/nix-daemon.service".to_owned())
        );
        assert_eq!(
            h.calls(),
            [(
                "readlink".into(),
                vec!["-f".into(), "/etc/systemd/system/nix-daemon.service".into()]
            )]
        );
    }

    #[test]
    fn test_store_path_returns_none_for_masked() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"/dev/null\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            h.inner
                .runtime
                .block_on(store_path_impl(&h.inner, "console-getty"))
                .unwrap(),
            None
        );
    }

    #[test]
    fn test_store_path_returns_none_for_not_found() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 1,
            stdout: b"".to_vec(),
            stderr: b"readlink: No such file or directory\n".to_vec(),
        }]);
        assert_eq!(
            h.inner
                .runtime
                .block_on(store_path_impl(&h.inner, "sshd"))
                .unwrap(),
            None
        );
    }

    #[test]
    fn test_enablement_status_linked() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"linked\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            h.inner
                .runtime
                .block_on(enablement_status_impl(&h.inner, "nix-daemon"))
                .unwrap(),
            "linked"
        );
        assert_eq!(
            h.calls(),
            [(
                "systemctl".into(),
                vec![
                    "show".into(),
                    "nix-daemon".into(),
                    "-p".into(),
                    "UnitFileState".into(),
                    "--value".into()
                ]
            )]
        );
    }

    #[test]
    fn test_enablement_status_enabled() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"enabled\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            h.inner
                .runtime
                .block_on(enablement_status_impl(&h.inner, "avahi-daemon"))
                .unwrap(),
            "enabled"
        );
    }

    #[test]
    fn test_enablement_status_masked() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"masked\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            h.inner
                .runtime
                .block_on(enablement_status_impl(&h.inner, "console-getty"))
                .unwrap(),
            "masked"
        );
    }

    #[test]
    fn test_exists_found() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"nix-daemon.service  enabled  enabled\nsshd.service  enabled  enabled\n"
                .to_vec(),
            stderr: vec![],
        }]);
        assert!(
            h.inner
                .runtime
                .block_on(exists_impl(&h.inner, "nix-daemon"))
                .unwrap()
        );
        assert_eq!(
            h.calls(),
            [(
                "systemctl".into(),
                vec!["list-unit-files".into(), "--no-pager".into()]
            )]
        );
    }

    #[test]
    fn test_exists_not_found() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"sshd.service  enabled  enabled\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            !h.inner
                .runtime
                .block_on(exists_impl(&h.inner, "nix-daemon"))
                .unwrap()
        );
    }

    #[test]
    fn test_properties_parse() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"Type=simple\nExecStart=/bin/foo\nDescription=\nActiveState=active\n".to_vec(),
            stderr: vec![],
        }]);
        let props = h
            .inner
            .runtime
            .block_on(properties_impl(&h.inner, "test"))
            .unwrap();
        assert_eq!(props.get("Type").unwrap(), "simple");
        assert_eq!(props.get("ExecStart").unwrap(), "/bin/foo");
        assert_eq!(props.get("ActiveState").unwrap(), "active");
        assert!(!props.contains_key("Description"));
        assert_eq!(
            h.calls(),
            [("systemctl".into(), vec!["show".into(), "test".into()])]
        );
    }
}
