use crate::backend::BackendError;
use crate::host::HostInner;

// ---------------------------------------------------------------------------
// Socket spec parsing
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub enum SocketSpec {
    Tcp { address: String, port: u16 },
    Udp { address: String, port: u16 },
    Unix { path: String },
}

pub fn parse_socket_spec(spec: &str) -> Result<SocketSpec, BackendError> {
    if let Some(rest) = spec.strip_prefix("tcp://") {
        let (address, port) = parse_host_port(rest, "tcp")?;
        Ok(SocketSpec::Tcp { address, port })
    } else if let Some(rest) = spec.strip_prefix("udp://") {
        let (address, port) = parse_host_port(rest, "udp")?;
        Ok(SocketSpec::Udp { address, port })
    } else if let Some(rest) = spec.strip_prefix("unix://") {
        if rest.is_empty() {
            return Err(BackendError::Execution("empty unix socket path".into()));
        }
        Ok(SocketSpec::Unix {
            path: rest.to_owned(),
        })
    } else {
        Err(BackendError::Execution(format!(
            "unknown socket scheme in: {spec}"
        )))
    }
}

fn parse_host_port(s: &str, proto: &str) -> Result<(String, u16), BackendError> {
    let (addr, port_str) = s
        .rsplit_once(':')
        .ok_or_else(|| BackendError::Execution(format!("missing port in {proto} spec: {s}")))?;
    let port = port_str.parse::<u16>().map_err(|_| {
        BackendError::Execution(format!("invalid port in {proto} spec: {port_str}"))
    })?;
    if addr.is_empty() {
        return Err(BackendError::Execution(format!(
            "empty address in {proto} spec: {s}"
        )));
    }
    Ok((addr.to_owned(), port))
}

// ---------------------------------------------------------------------------
// Layer 1 — Async core functions
// ---------------------------------------------------------------------------

pub async fn is_listening_impl(inner: &HostInner, spec: &str) -> Result<bool, BackendError> {
    let parsed = parse_socket_spec(spec)?;
    match &parsed {
        SocketSpec::Tcp { address, port } => {
            let needle = format!("{address}:{port}");
            let out = inner.execute("ss", &["-lnH", "-t"]).await?;
            Ok(out.lines().any(|line| line.contains(&needle)))
        }
        SocketSpec::Udp { address, port } => {
            let needle = format!("{address}:{port}");
            let out = inner.execute("ss", &["-lnH", "-u"]).await?;
            Ok(out.lines().any(|line| line.contains(&needle)))
        }
        SocketSpec::Unix { path } => {
            let out = inner.execute("ss", &["-lnH", "-x"]).await?;
            Ok(out.lines().any(|line| line.contains(path.as_str())))
        }
    }
}

// ---------------------------------------------------------------------------
// Layers 2 + 3 — Generated by macro (is_listening only)
// ---------------------------------------------------------------------------

oxi_nixinfra_macros::nix_module! {
    Socket {
        fields { spec: String },
        new(spec: &str) {
            spec: spec.to_owned(),
        },
        methods {
            fn is_listening() -> bool => is_listening_impl;
        }
    }
}

// Manual getter methods (pure parsing, no shell commands)
#[pyo3::prelude::pymethods]
impl Socket {
    fn protocol(&self) -> pyo3::prelude::PyResult<String> {
        let parsed = parse_socket_spec(&self.spec).map_err(crate::helpers::backend_err_to_py)?;
        Ok(match parsed {
            SocketSpec::Tcp { .. } => "tcp".to_owned(),
            SocketSpec::Udp { .. } => "udp".to_owned(),
            SocketSpec::Unix { .. } => "unix".to_owned(),
        })
    }

    fn address(&self) -> pyo3::prelude::PyResult<String> {
        let parsed = parse_socket_spec(&self.spec).map_err(crate::helpers::backend_err_to_py)?;
        Ok(match parsed {
            SocketSpec::Tcp { address, .. } | SocketSpec::Udp { address, .. } => address,
            SocketSpec::Unix { path } => path,
        })
    }

    fn port(&self) -> pyo3::prelude::PyResult<Option<u16>> {
        let parsed = parse_socket_spec(&self.spec).map_err(crate::helpers::backend_err_to_py)?;
        Ok(match parsed {
            SocketSpec::Tcp { port, .. } | SocketSpec::Udp { port, .. } => Some(port),
            SocketSpec::Unix { .. } => None,
        })
    }
}

#[pyo3::prelude::pymethods]
impl AsyncSocket {
    fn protocol(&self) -> pyo3::prelude::PyResult<String> {
        let parsed = parse_socket_spec(&self.spec).map_err(crate::helpers::backend_err_to_py)?;
        Ok(match parsed {
            SocketSpec::Tcp { .. } => "tcp".to_owned(),
            SocketSpec::Udp { .. } => "udp".to_owned(),
            SocketSpec::Unix { .. } => "unix".to_owned(),
        })
    }

    fn address(&self) -> pyo3::prelude::PyResult<String> {
        let parsed = parse_socket_spec(&self.spec).map_err(crate::helpers::backend_err_to_py)?;
        Ok(match parsed {
            SocketSpec::Tcp { address, .. } | SocketSpec::Udp { address, .. } => address,
            SocketSpec::Unix { path } => path,
        })
    }

    fn port(&self) -> pyo3::prelude::PyResult<Option<u16>> {
        let parsed = parse_socket_spec(&self.spec).map_err(crate::helpers::backend_err_to_py)?;
        Ok(match parsed {
            SocketSpec::Tcp { port, .. } | SocketSpec::Udp { port, .. } => Some(port),
            SocketSpec::Unix { .. } => None,
        })
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::mock::MockBackend;
    use crate::command::RawOutput;

    fn make_inner(responses: Vec<RawOutput>) -> HostInner {
        HostInner {
            backend: Box::new(MockBackend::new(responses)),
            runtime: tokio::runtime::Runtime::new().unwrap(),
            connection_string: "mock://".to_owned(),
        }
    }

    #[test]
    fn test_parse_tcp() {
        let spec = parse_socket_spec("tcp://0.0.0.0:22").unwrap();
        assert!(
            matches!(spec, SocketSpec::Tcp { ref address, port } if address == "0.0.0.0" && port == 22)
        );
    }

    #[test]
    fn test_parse_udp() {
        let spec = parse_socket_spec("udp://127.0.0.1:53").unwrap();
        assert!(
            matches!(spec, SocketSpec::Udp { ref address, port } if address == "127.0.0.1" && port == 53)
        );
    }

    #[test]
    fn test_parse_unix() {
        let spec = parse_socket_spec("unix:///var/run/docker.sock").unwrap();
        assert!(matches!(spec, SocketSpec::Unix { ref path } if path == "/var/run/docker.sock"));
    }

    #[test]
    fn test_parse_unknown_scheme() {
        let err = parse_socket_spec("http://localhost:80").unwrap_err();
        assert!(err.to_string().contains("unknown socket scheme"));
    }

    #[test]
    fn test_parse_missing_port() {
        let err = parse_socket_spec("tcp://0.0.0.0").unwrap_err();
        assert!(err.to_string().contains("missing port"));
    }

    #[test]
    fn test_parse_empty_unix_path() {
        let err = parse_socket_spec("unix://").unwrap_err();
        assert!(err.to_string().contains("empty unix socket path"));
    }

    #[test]
    fn test_is_listening_tcp_found() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout:
                b"LISTEN  0  128  0.0.0.0:22  0.0.0.0:*\nLISTEN  0  128  0.0.0.0:80  0.0.0.0:*\n"
                    .to_vec(),
            stderr: vec![],
        }]);
        assert!(
            inner
                .runtime
                .block_on(is_listening_impl(&inner, "tcp://0.0.0.0:22"))
                .unwrap()
        );
    }

    #[test]
    fn test_is_listening_tcp_not_found() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"LISTEN  0  128  0.0.0.0:80  0.0.0.0:*\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            !inner
                .runtime
                .block_on(is_listening_impl(&inner, "tcp://0.0.0.0:22"))
                .unwrap()
        );
    }

    #[test]
    fn test_is_listening_unix_found() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"u_str  LISTEN  0  128  /var/run/docker.sock  12345  * 0\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            inner
                .runtime
                .block_on(is_listening_impl(&inner, "unix:///var/run/docker.sock"))
                .unwrap()
        );
    }

    #[test]
    fn test_is_listening_unix_not_found() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"u_str  LISTEN  0  128  /var/run/other.sock  12345  * 0\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            !inner
                .runtime
                .block_on(is_listening_impl(&inner, "unix:///var/run/docker.sock"))
                .unwrap()
        );
    }
}
