use crate::backend::BackendError;
use crate::host::HostInner;

// ---------------------------------------------------------------------------
// Layer 1 — Async core functions
// ---------------------------------------------------------------------------

pub async fn value_impl(inner: &HostInner, key: &str) -> Result<String, BackendError> {
    let out = inner.execute("sysctl", &["-n", key]).await?;
    if out.rc == 0 {
        let stdout = String::from_utf8_lossy(&out.stdout);
        Ok(stdout.trim().to_owned())
    } else {
        Err(BackendError::Execution(format!(
            "sysctl failed for '{}': {}",
            key,
            String::from_utf8_lossy(&out.stderr)
        )))
    }
}

pub async fn exists_impl(inner: &HostInner, key: &str) -> Result<bool, BackendError> {
    let out = inner.execute("sysctl", &["-n", key]).await?;
    Ok(out.rc == 0)
}

// ---------------------------------------------------------------------------
// Layers 2 + 3 — Generated by macro
// ---------------------------------------------------------------------------

oxi_nixinfra_macros::nix_module! {
    Sysctl {
        fields { key: String },
        new(key: &str) {
            key: key.to_owned(),
        },
        methods {
            fn value() -> String => value_impl;
            fn exists() -> bool => exists_impl;
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::mock::MockBackend;
    use crate::command::RawOutput;

    fn make_inner(responses: Vec<RawOutput>) -> HostInner {
        HostInner {
            backend: Box::new(MockBackend::new(responses)),
            runtime: tokio::runtime::Runtime::new().unwrap(),
            connection_string: "mock://".to_owned(),
        }
    }

    #[test]
    fn test_value_returns_trimmed() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"1\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            inner
                .runtime
                .block_on(value_impl(&inner, "net.ipv4.ip_forward"))
                .unwrap(),
            "1"
        );
    }

    #[test]
    fn test_value_error_on_unknown_key() {
        let inner = make_inner(vec![RawOutput {
            rc: 1,
            stdout: vec![],
            stderr: b"sysctl: cannot stat /proc/sys/nonexistent: No such file or directory\n"
                .to_vec(),
        }]);
        let err = inner
            .runtime
            .block_on(value_impl(&inner, "nonexistent"))
            .unwrap_err();
        assert!(err.to_string().contains("sysctl failed"));
    }

    #[test]
    fn test_exists_true() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"1\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            inner
                .runtime
                .block_on(exists_impl(&inner, "net.ipv4.ip_forward"))
                .unwrap()
        );
    }

    #[test]
    fn test_exists_false() {
        let inner = make_inner(vec![RawOutput {
            rc: 1,
            stdout: vec![],
            stderr: b"sysctl: cannot stat /proc/sys/nonexistent: No such file or directory\n"
                .to_vec(),
        }]);
        assert!(
            !inner
                .runtime
                .block_on(exists_impl(&inner, "nonexistent"))
                .unwrap()
        );
    }
}
