use crate::backend::BackendError;
use crate::host::HostInner;

// ---------------------------------------------------------------------------
// Layer 1 — Async core functions
// ---------------------------------------------------------------------------

pub async fn value_impl(inner: &HostInner, key: &str) -> Result<String, BackendError> {
    let out = inner.execute("sysctl", &["-n", key]).await?;
    if out.rc() == 0 {
        Ok(out.stdout().to_owned())
    } else {
        Err(BackendError::Execution(format!(
            "sysctl failed for '{}': {}",
            key,
            out.stderr_lossy()
        )))
    }
}

pub async fn exists_impl(inner: &HostInner, key: &str) -> Result<bool, BackendError> {
    let out = inner.execute("sysctl", &["-n", key]).await?;
    Ok(out.rc() == 0)
}

// ---------------------------------------------------------------------------
// Layers 2 + 3 — Generated by macro
// ---------------------------------------------------------------------------

oxi_nixinfra_macros::nix_module! {
    Sysctl {
        fields { key: String },
        new(key: &str) {
            key: key.to_owned(),
        },
        methods {
            fn value() -> String => value_impl;
            fn exists() -> bool => exists_impl;
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::mock::TestHarness;
    use crate::command::RawOutput;

    #[test]
    fn test_value_returns_trimmed() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"1\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            h.inner
                .runtime
                .block_on(value_impl(&h.inner, "net.ipv4.ip_forward"))
                .unwrap(),
            "1"
        );
        assert_eq!(
            h.calls(),
            [(
                "sysctl".into(),
                vec!["-n".into(), "net.ipv4.ip_forward".into()]
            )]
        );
    }

    #[test]
    fn test_value_error_on_unknown_key() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 1,
            stdout: vec![],
            stderr: b"sysctl: cannot stat /proc/sys/nonexistent: No such file or directory\n"
                .to_vec(),
        }]);
        let err = h
            .inner
            .runtime
            .block_on(value_impl(&h.inner, "nonexistent"))
            .unwrap_err();
        assert!(err.to_string().contains("sysctl failed"));
    }

    #[test]
    fn test_exists_true() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"1\n".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            h.inner
                .runtime
                .block_on(exists_impl(&h.inner, "net.ipv4.ip_forward"))
                .unwrap()
        );
        assert_eq!(
            h.calls(),
            [(
                "sysctl".into(),
                vec!["-n".into(), "net.ipv4.ip_forward".into()]
            )]
        );
    }

    #[test]
    fn test_exists_false() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 1,
            stdout: vec![],
            stderr: b"sysctl: cannot stat /proc/sys/nonexistent: No such file or directory\n"
                .to_vec(),
        }]);
        assert!(
            !h.inner
                .runtime
                .block_on(exists_impl(&h.inner, "nonexistent"))
                .unwrap()
        );
    }
}
