use crate::backend::BackendError;
use crate::host::HostInner;

// ---------------------------------------------------------------------------
// Boot info struct
// ---------------------------------------------------------------------------

pub struct BootInfo {
    pub kernel_version: String,
    pub arch: String,
    pub label: String,
}

fn parse_kernel_version(kernel_path: &str) -> String {
    kernel_path
        .rsplit('/')
        .nth(1)
        .and_then(|dir| dir.get(33..))
        .and_then(|s| s.strip_prefix("linux-"))
        .unwrap_or("unknown")
        .to_owned()
}

// ---------------------------------------------------------------------------
// Layer 1 — Async core functions
// ---------------------------------------------------------------------------

pub async fn nixos_version_impl(inner: &HostInner) -> Result<String, BackendError> {
    let out = inner
        .execute("cat", &["/run/current-system/nixos-version"])
        .await?;
    Ok(out.stdout().to_owned())
}

pub async fn system_profile_impl(inner: &HostInner) -> Result<String, BackendError> {
    let out = inner.execute("readlink", &["/run/current-system"]).await?;
    Ok(out.stdout().to_owned())
}

pub async fn generation_count_impl(inner: &HostInner) -> Result<i32, BackendError> {
    let out = inner
        .execute("ls", &["-1", "/nix/var/nix/profiles/"])
        .await?;
    let count = out
        .lines()
        .filter(|line| line.starts_with("system-") && line.ends_with("-link"))
        .count();
    #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
    Ok(count as i32)
}

pub async fn boot_info_impl(inner: &HostInner) -> Result<BootInfo, BackendError> {
    let out = inner
        .execute("cat", &["/run/current-system/boot.json"])
        .await?;
    let kernel_path = out.json_field("kernel").unwrap_or_default();
    Ok(BootInfo {
        kernel_version: parse_kernel_version(&kernel_path),
        arch: out.json_field("system").unwrap_or_default(),
        label: out.json_field("label").unwrap_or_default(),
    })
}

pub async fn specialisations_impl(inner: &HostInner) -> Result<Vec<String>, BackendError> {
    let out = inner
        .execute("ls", &["-1", "/run/current-system/specialisation/"])
        .await?;
    Ok(out
        .lines()
        .filter(|l| !l.is_empty())
        .map(ToOwned::to_owned)
        .collect())
}

// ---------------------------------------------------------------------------
// Layer 2 + 3 — Sync and async wrappers (generated by macro)
// ---------------------------------------------------------------------------

oxi_nixinfra_macros::nix_module! {
    SystemInfo {
        fields {},
        cache {
            boot_info_cache: std::sync::OnceLock<BootInfo>,
        },
        new() {
            boot_info_cache: std::sync::OnceLock::new(),
        },
        methods {
            fn nixos_version() -> String => nixos_version_impl;
            fn system_profile() -> String => system_profile_impl;
            fn generation_count() -> i32 => generation_count_impl;
            fn specialisations() -> Vec<String> => specialisations_impl;
        }
    }
}

// Private helper — NOT a pymethod
impl SystemInfo {
    fn cached_boot_info(&self) -> pyo3::prelude::PyResult<&BootInfo> {
        if let Some(cached) = self.boot_info_cache.get() {
            return Ok(cached);
        }
        let info = self
            .inner
            .runtime
            .block_on(boot_info_impl(&self.inner))
            .map_err(crate::helpers::backend_err_to_py)?;
        // Another thread may have raced us; that's fine — OnceLock ignores
        // the second set and we return whichever value won.
        let _ = self.boot_info_cache.set(info);
        Ok(self.boot_info_cache.get().expect("just set"))
    }
}

// Methods that don't follow the standard pattern (extract fields from BootInfo)
#[pyo3::prelude::pymethods]
impl SystemInfo {
    fn kernel_version(&self) -> pyo3::prelude::PyResult<String> {
        Ok(self.cached_boot_info()?.kernel_version.clone())
    }

    fn arch(&self) -> pyo3::prelude::PyResult<String> {
        Ok(self.cached_boot_info()?.arch.clone())
    }

    fn label(&self) -> pyo3::prelude::PyResult<String> {
        Ok(self.cached_boot_info()?.label.clone())
    }
}

#[pyo3::prelude::pymethods]
impl AsyncSystemInfo {
    fn kernel_version<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let info = boot_info_impl(&inner)
                .await
                .map_err(crate::helpers::backend_err_to_py)?;
            Ok(info.kernel_version)
        })
    }

    fn arch<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let info = boot_info_impl(&inner)
                .await
                .map_err(crate::helpers::backend_err_to_py)?;
            Ok(info.arch)
        })
    }

    fn label<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let info = boot_info_impl(&inner)
                .await
                .map_err(crate::helpers::backend_err_to_py)?;
            Ok(info.label)
        })
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::mock::TestHarness;
    use crate::command::RawOutput;

    #[test]
    fn test_nixos_version() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"25.11.9840.a4bf06618f0b".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            h.inner
                .runtime
                .block_on(nixos_version_impl(&h.inner))
                .unwrap(),
            "25.11.9840.a4bf06618f0b"
        );
        assert_eq!(
            h.calls(),
            [(
                "cat".into(),
                vec!["/run/current-system/nixos-version".into()]
            )]
        );
    }

    #[test]
    fn test_system_profile() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"/nix/store/abc123-nixos-system-nixos-25.11\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            h.inner
                .runtime
                .block_on(system_profile_impl(&h.inner))
                .unwrap(),
            "/nix/store/abc123-nixos-system-nixos-25.11"
        );
        assert_eq!(
            h.calls(),
            [("readlink".into(), vec!["/run/current-system".into()])]
        );
    }

    #[test]
    fn test_generation_count() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"system-1-link\nsystem-2-link\nsystem-3-link\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            h.inner
                .runtime
                .block_on(generation_count_impl(&h.inner))
                .unwrap(),
            3
        );
        assert_eq!(
            h.calls(),
            [(
                "ls".into(),
                vec!["-1".into(), "/nix/var/nix/profiles/".into()]
            )]
        );
    }

    #[test]
    fn test_boot_info_parsing_compact() {
        let boot_json = br#"{"org.nixos.bootspec.v1":{"kernel":"/nix/store/abc123abc123abc123abc123abc123ab-linux-6.12.83/bzImage","system":"x86_64-linux","label":"NixOS Xantusia 25.11 (Linux 6.12.83)"},"org.nixos.specialisation.v1":{}}"#;
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: boot_json.to_vec(),
            stderr: vec![],
        }]);
        let info = h.inner.runtime.block_on(boot_info_impl(&h.inner)).unwrap();
        assert_eq!(info.kernel_version, "6.12.83");
        assert_eq!(info.arch, "x86_64-linux");
        assert_eq!(info.label, "NixOS Xantusia 25.11 (Linux 6.12.83)");
        assert_eq!(
            h.calls(),
            [("cat".into(), vec!["/run/current-system/boot.json".into()])]
        );
    }

    #[test]
    fn test_boot_info_parsing_spaced() {
        let boot_json = br#"{"org.nixos.bootspec.v1": {"kernel": "/nix/store/abc123abc123abc123abc123abc123ab-linux-6.12.83/bzImage", "system": "x86_64-linux", "label": "NixOS Xantusia 25.11 (Linux 6.12.83)"}}"#;
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: boot_json.to_vec(),
            stderr: vec![],
        }]);
        let info = h.inner.runtime.block_on(boot_info_impl(&h.inner)).unwrap();
        assert_eq!(info.kernel_version, "6.12.83");
        assert_eq!(info.arch, "x86_64-linux");
        assert_eq!(info.label, "NixOS Xantusia 25.11 (Linux 6.12.83)");
    }

    #[test]
    fn test_specialisations_empty() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"".to_vec(),
            stderr: vec![],
        }]);
        let specs = h
            .inner
            .runtime
            .block_on(specialisations_impl(&h.inner))
            .unwrap();
        assert!(specs.is_empty());
        assert_eq!(
            h.calls(),
            [(
                "ls".into(),
                vec!["-1".into(), "/run/current-system/specialisation/".into()]
            )]
        );
    }

    #[test]
    fn test_specialisations_some() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"gaming\nwork\n".to_vec(),
            stderr: vec![],
        }]);
        let specs = h
            .inner
            .runtime
            .block_on(specialisations_impl(&h.inner))
            .unwrap();
        assert_eq!(specs, vec!["gaming", "work"]);
    }

    #[test]
    fn test_parse_kernel_version() {
        assert_eq!(
            parse_kernel_version(
                "/nix/store/abc123abc123abc123abc123abc123ab-linux-6.12.83/bzImage"
            ),
            "6.12.83"
        );
    }

    #[test]
    fn test_parse_kernel_version_unknown() {
        assert_eq!(parse_kernel_version(""), "unknown");
    }

    #[test]
    fn test_boot_info_cached_across_calls() {
        let boot_json = br#"{"org.nixos.bootspec.v1":{"kernel":"/nix/store/abc123abc123abc123abc123abc123ab-linux-6.12.83/bzImage","system":"x86_64-linux","label":"NixOS Xantusia 25.11 (Linux 6.12.83)"}}"#;
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: boot_json.to_vec(),
            stderr: vec![],
        }]);
        let inner = std::sync::Arc::new(h.inner);
        let sys = SystemInfo {
            inner: std::sync::Arc::clone(&inner),
            boot_info_cache: std::sync::OnceLock::new(),
        };
        // First call populates cache (consumes the one mock response)
        let info1 = sys.cached_boot_info().unwrap();
        assert_eq!(info1.kernel_version, "6.12.83");
        // Second call hits cache (no mock response needed — would panic otherwise)
        let info2 = sys.cached_boot_info().unwrap();
        assert_eq!(info2.arch, "x86_64-linux");
        // Third call also cached
        let info3 = sys.cached_boot_info().unwrap();
        assert_eq!(info3.label, "NixOS Xantusia 25.11 (Linux 6.12.83)");
    }
}
