use crate::backend::BackendError;
use crate::host::HostInner;

// ---------------------------------------------------------------------------
// Boot info struct
// ---------------------------------------------------------------------------

pub struct BootInfo {
    pub kernel_version: String,
    pub arch: String,
    pub label: String,
}

fn parse_kernel_version(kernel_path: &str) -> String {
    kernel_path
        .rsplit('/')
        .nth(1)
        .and_then(|dir| dir.get(33..))
        .and_then(|s| s.strip_prefix("linux-"))
        .unwrap_or("unknown")
        .to_owned()
}

// ---------------------------------------------------------------------------
// Layer 1 — Async core functions
// ---------------------------------------------------------------------------

pub async fn nixos_version_impl(inner: &HostInner) -> Result<String, BackendError> {
    let out = inner
        .execute("cat", &["/run/current-system/nixos-version"])
        .await?;
    Ok(out.stdout().to_owned())
}

pub async fn system_profile_impl(inner: &HostInner) -> Result<String, BackendError> {
    let out = inner.execute("readlink", &["/run/current-system"]).await?;
    Ok(out.stdout().to_owned())
}

pub async fn generation_count_impl(inner: &HostInner) -> Result<i32, BackendError> {
    let out = inner
        .execute("ls", &["-1", "/nix/var/nix/profiles/"])
        .await?;
    let count = out
        .lines()
        .filter(|line| line.starts_with("system-") && line.ends_with("-link"))
        .count();
    #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
    Ok(count as i32)
}

pub async fn boot_info_impl(inner: &HostInner) -> Result<BootInfo, BackendError> {
    let out = inner
        .execute("cat", &["/run/current-system/boot.json"])
        .await?;
    let kernel_path = out.json_field("kernel").unwrap_or_default();
    Ok(BootInfo {
        kernel_version: parse_kernel_version(&kernel_path),
        arch: out.json_field("system").unwrap_or_default(),
        label: out.json_field("label").unwrap_or_default(),
    })
}

pub async fn specialisations_impl(inner: &HostInner) -> Result<Vec<String>, BackendError> {
    let out = inner
        .execute("ls", &["-1", "/run/current-system/specialisation/"])
        .await?;
    Ok(out
        .lines()
        .filter(|l| !l.is_empty())
        .map(ToOwned::to_owned)
        .collect())
}

// ---------------------------------------------------------------------------
// Layer 2 + 3 — Sync and async wrappers (generated by macro)
// ---------------------------------------------------------------------------

oxi_nixinfra_macros::nix_module! {
    SystemInfo {
        fields {},
        new() {},
        methods {
            fn nixos_version() -> String => nixos_version_impl;
            fn system_profile() -> String => system_profile_impl;
            fn generation_count() -> i32 => generation_count_impl;
            fn specialisations() -> Vec<String> => specialisations_impl;
        }
    }
}

// Methods that don't follow the standard pattern (extract fields from BootInfo)
#[pyo3::prelude::pymethods]
impl SystemInfo {
    fn kernel_version(&self) -> pyo3::prelude::PyResult<String> {
        let info = crate::helpers::wrap_sync(&self.inner, boot_info_impl(&self.inner))?;
        Ok(info.kernel_version)
    }

    fn arch(&self) -> pyo3::prelude::PyResult<String> {
        let info = crate::helpers::wrap_sync(&self.inner, boot_info_impl(&self.inner))?;
        Ok(info.arch)
    }

    fn label(&self) -> pyo3::prelude::PyResult<String> {
        let info = crate::helpers::wrap_sync(&self.inner, boot_info_impl(&self.inner))?;
        Ok(info.label)
    }
}

#[pyo3::prelude::pymethods]
impl AsyncSystemInfo {
    fn kernel_version<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let info = boot_info_impl(&inner)
                .await
                .map_err(crate::helpers::backend_err_to_py)?;
            Ok(info.kernel_version)
        })
    }

    fn arch<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let info = boot_info_impl(&inner)
                .await
                .map_err(crate::helpers::backend_err_to_py)?;
            Ok(info.arch)
        })
    }

    fn label<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let info = boot_info_impl(&inner)
                .await
                .map_err(crate::helpers::backend_err_to_py)?;
            Ok(info.label)
        })
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::mock::MockBackend;
    use crate::command::RawOutput;

    fn make_inner(responses: Vec<RawOutput>) -> HostInner {
        HostInner {
            backend: Box::new(MockBackend::new(responses)),
            runtime: tokio::runtime::Runtime::new().unwrap(),
            connection_string: "mock://".to_owned(),
        }
    }

    #[test]
    fn test_nixos_version() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"25.11.9840.a4bf06618f0b".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            inner.runtime.block_on(nixos_version_impl(&inner)).unwrap(),
            "25.11.9840.a4bf06618f0b"
        );
    }

    #[test]
    fn test_system_profile() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"/nix/store/abc123-nixos-system-nixos-25.11\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            inner.runtime.block_on(system_profile_impl(&inner)).unwrap(),
            "/nix/store/abc123-nixos-system-nixos-25.11"
        );
    }

    #[test]
    fn test_generation_count() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"system-1-link\nsystem-2-link\nsystem-3-link\n".to_vec(),
            stderr: vec![],
        }]);
        assert_eq!(
            inner
                .runtime
                .block_on(generation_count_impl(&inner))
                .unwrap(),
            3
        );
    }

    #[test]
    fn test_boot_info_parsing_compact() {
        let boot_json = br#"{"org.nixos.bootspec.v1":{"kernel":"/nix/store/abc123abc123abc123abc123abc123ab-linux-6.12.83/bzImage","system":"x86_64-linux","label":"NixOS Xantusia 25.11 (Linux 6.12.83)"},"org.nixos.specialisation.v1":{}}"#;
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: boot_json.to_vec(),
            stderr: vec![],
        }]);
        let info = inner.runtime.block_on(boot_info_impl(&inner)).unwrap();
        assert_eq!(info.kernel_version, "6.12.83");
        assert_eq!(info.arch, "x86_64-linux");
        assert_eq!(info.label, "NixOS Xantusia 25.11 (Linux 6.12.83)");
    }

    #[test]
    fn test_boot_info_parsing_spaced() {
        let boot_json = br#"{"org.nixos.bootspec.v1": {"kernel": "/nix/store/abc123abc123abc123abc123abc123ab-linux-6.12.83/bzImage", "system": "x86_64-linux", "label": "NixOS Xantusia 25.11 (Linux 6.12.83)"}}"#;
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: boot_json.to_vec(),
            stderr: vec![],
        }]);
        let info = inner.runtime.block_on(boot_info_impl(&inner)).unwrap();
        assert_eq!(info.kernel_version, "6.12.83");
        assert_eq!(info.arch, "x86_64-linux");
        assert_eq!(info.label, "NixOS Xantusia 25.11 (Linux 6.12.83)");
    }

    #[test]
    fn test_specialisations_empty() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"".to_vec(),
            stderr: vec![],
        }]);
        let specs = inner
            .runtime
            .block_on(specialisations_impl(&inner))
            .unwrap();
        assert!(specs.is_empty());
    }

    #[test]
    fn test_specialisations_some() {
        let inner = make_inner(vec![RawOutput {
            rc: 0,
            stdout: b"gaming\nwork\n".to_vec(),
            stderr: vec![],
        }]);
        let specs = inner
            .runtime
            .block_on(specialisations_impl(&inner))
            .unwrap();
        assert_eq!(specs, vec!["gaming", "work"]);
    }

    #[test]
    fn test_parse_kernel_version() {
        assert_eq!(
            parse_kernel_version(
                "/nix/store/abc123abc123abc123abc123abc123ab-linux-6.12.83/bzImage"
            ),
            "6.12.83"
        );
    }

    #[test]
    fn test_parse_kernel_version_unknown() {
        assert_eq!(parse_kernel_version(""), "unknown");
    }
}
