use crate::backend::BackendError;
use crate::host::HostInner;

// ---------------------------------------------------------------------------
// Layer 1 — Async core functions
// ---------------------------------------------------------------------------

pub async fn exists_impl(inner: &HostInner, name: &str) -> Result<bool, BackendError> {
    let out = inner.execute("id", &[name]).await?;
    Ok(out.rc() == 0)
}

pub async fn name_impl(inner: &HostInner) -> Result<String, BackendError> {
    let out = inner.execute("id", &["-nu"]).await?;
    Ok(out.stdout().to_owned())
}

pub async fn uid_impl(inner: &HostInner, name: &str) -> Result<i32, BackendError> {
    let out = inner.execute("id", &["-u", name]).await?;
    out.parse_int("uid")
}

pub async fn gid_impl(inner: &HostInner, name: &str) -> Result<i32, BackendError> {
    let out = inner.execute("id", &["-g", name]).await?;
    out.parse_int("gid")
}

pub async fn group_impl(inner: &HostInner, name: &str) -> Result<String, BackendError> {
    let out = inner.execute("id", &["-ng", name]).await?;
    Ok(out.stdout().to_owned())
}

pub async fn groups_impl(inner: &HostInner, name: &str) -> Result<Vec<String>, BackendError> {
    let out = inner.execute("id", &["-nG", name]).await?;
    Ok(out
        .stdout()
        .split_whitespace()
        .map(ToOwned::to_owned)
        .collect())
}

async fn getent_field(inner: &HostInner, name: &str, index: usize) -> Result<String, BackendError> {
    let out = inner.execute("getent", &["passwd", name]).await?;
    out.delimited_field(
        ':',
        index,
        &format!("getent field {index} for user: {name}"),
    )
    .map(ToOwned::to_owned)
}

pub async fn home_impl(inner: &HostInner, name: &str) -> Result<String, BackendError> {
    getent_field(inner, name, 5).await
}

pub async fn shell_impl(inner: &HostInner, name: &str) -> Result<String, BackendError> {
    getent_field(inner, name, 6).await
}

pub async fn is_declared_impl(inner: &HostInner, name: &str) -> Result<bool, BackendError> {
    let out = inner
        .execute(
            "grep",
            &[
                "-oP",
                r"/nix/store/[a-z0-9]+-users-groups\.json",
                "/run/current-system/activate",
            ],
        )
        .await?;
    if out.rc() != 0 {
        return Ok(false);
    }
    let manifest_path = out.stdout();
    if manifest_path.is_empty() {
        return Ok(false);
    }
    let manifest = inner.execute("cat", &[manifest_path]).await?;
    if manifest.rc() != 0 {
        return Ok(false);
    }
    let needle = format!("\"name\":\"{name}\"");
    Ok(manifest.stdout().contains(&needle))
}

/// Resolve the effective user name: use stored name if present, otherwise run `id -nu`.
async fn resolve_name(inner: &HostInner, name: &Option<String>) -> Result<String, BackendError> {
    match name {
        Some(n) => Ok(n.clone()),
        None => name_impl(inner).await,
    }
}

// ---------------------------------------------------------------------------
// Layer 2 + 3 — Sync and async wrappers (generated by macro + manual)
// ---------------------------------------------------------------------------

oxi_nixinfra_macros::nix_module! {
    User {
        fields { name: Option<String> },
        new(name: Option<&str>) {
            name: name.map(std::borrow::ToOwned::to_owned),
        },
        methods {}
    }
}

// All methods are manual (resolve_name pattern)
#[pyo3::prelude::pymethods]
impl User {
    fn exists(&self) -> pyo3::prelude::PyResult<bool> {
        let inner = &self.inner;
        let name = crate::helpers::wrap_sync(inner, resolve_name(inner, &self.name))?;
        crate::helpers::wrap_sync(inner, exists_impl(inner, &name))
    }

    fn name(&self) -> pyo3::prelude::PyResult<String> {
        match &self.name {
            Some(n) => Ok(n.clone()),
            None => crate::helpers::wrap_sync(&self.inner, name_impl(&self.inner)),
        }
    }

    fn uid(&self) -> pyo3::prelude::PyResult<i32> {
        let inner = &self.inner;
        let name = crate::helpers::wrap_sync(inner, resolve_name(inner, &self.name))?;
        crate::helpers::wrap_sync(inner, uid_impl(inner, &name))
    }

    fn gid(&self) -> pyo3::prelude::PyResult<i32> {
        let inner = &self.inner;
        let name = crate::helpers::wrap_sync(inner, resolve_name(inner, &self.name))?;
        crate::helpers::wrap_sync(inner, gid_impl(inner, &name))
    }

    fn group(&self) -> pyo3::prelude::PyResult<String> {
        let inner = &self.inner;
        let name = crate::helpers::wrap_sync(inner, resolve_name(inner, &self.name))?;
        crate::helpers::wrap_sync(inner, group_impl(inner, &name))
    }

    fn groups(&self) -> pyo3::prelude::PyResult<Vec<String>> {
        let inner = &self.inner;
        let name = crate::helpers::wrap_sync(inner, resolve_name(inner, &self.name))?;
        crate::helpers::wrap_sync(inner, groups_impl(inner, &name))
    }

    fn home(&self) -> pyo3::prelude::PyResult<String> {
        let inner = &self.inner;
        let name = crate::helpers::wrap_sync(inner, resolve_name(inner, &self.name))?;
        crate::helpers::wrap_sync(inner, home_impl(inner, &name))
    }

    fn shell(&self) -> pyo3::prelude::PyResult<String> {
        let inner = &self.inner;
        let name = crate::helpers::wrap_sync(inner, resolve_name(inner, &self.name))?;
        crate::helpers::wrap_sync(inner, shell_impl(inner, &name))
    }

    fn is_declared(&self) -> pyo3::prelude::PyResult<bool> {
        let inner = &self.inner;
        let name = crate::helpers::wrap_sync(inner, resolve_name(inner, &self.name))?;
        crate::helpers::wrap_sync(inner, is_declared_impl(inner, &name))
    }

    fn __repr__(&self) -> String {
        match &self.name {
            Some(n) => format!("<User {n}>"),
            None => "<User (current)>".to_owned(),
        }
    }
}

#[pyo3::prelude::pymethods]
impl AsyncUser {
    fn exists<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        let name = self.name.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let resolved = resolve_name(&inner, &name)
                .await
                .map_err(crate::helpers::backend_err_to_py)?;
            exists_impl(&inner, &resolved)
                .await
                .map_err(crate::helpers::backend_err_to_py)
        })
    }

    fn name<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        let name = self.name.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            match name {
                Some(n) => Ok(n),
                None => name_impl(&inner)
                    .await
                    .map_err(crate::helpers::backend_err_to_py),
            }
        })
    }

    fn uid<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        let name = self.name.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let resolved = resolve_name(&inner, &name)
                .await
                .map_err(crate::helpers::backend_err_to_py)?;
            uid_impl(&inner, &resolved)
                .await
                .map_err(crate::helpers::backend_err_to_py)
        })
    }

    fn gid<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        let name = self.name.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let resolved = resolve_name(&inner, &name)
                .await
                .map_err(crate::helpers::backend_err_to_py)?;
            gid_impl(&inner, &resolved)
                .await
                .map_err(crate::helpers::backend_err_to_py)
        })
    }

    fn group<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        let name = self.name.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let resolved = resolve_name(&inner, &name)
                .await
                .map_err(crate::helpers::backend_err_to_py)?;
            group_impl(&inner, &resolved)
                .await
                .map_err(crate::helpers::backend_err_to_py)
        })
    }

    fn groups<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        let name = self.name.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let resolved = resolve_name(&inner, &name)
                .await
                .map_err(crate::helpers::backend_err_to_py)?;
            groups_impl(&inner, &resolved)
                .await
                .map_err(crate::helpers::backend_err_to_py)
        })
    }

    fn home<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        let name = self.name.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let resolved = resolve_name(&inner, &name)
                .await
                .map_err(crate::helpers::backend_err_to_py)?;
            home_impl(&inner, &resolved)
                .await
                .map_err(crate::helpers::backend_err_to_py)
        })
    }

    fn shell<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        let name = self.name.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let resolved = resolve_name(&inner, &name)
                .await
                .map_err(crate::helpers::backend_err_to_py)?;
            shell_impl(&inner, &resolved)
                .await
                .map_err(crate::helpers::backend_err_to_py)
        })
    }

    fn is_declared<'py>(
        &self,
        py: pyo3::prelude::Python<'py>,
    ) -> pyo3::prelude::PyResult<pyo3::prelude::Bound<'py, pyo3::prelude::PyAny>> {
        let inner = self.inner.clone();
        let name = self.name.clone();
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let resolved = resolve_name(&inner, &name)
                .await
                .map_err(crate::helpers::backend_err_to_py)?;
            is_declared_impl(&inner, &resolved)
                .await
                .map_err(crate::helpers::backend_err_to_py)
        })
    }

    fn __repr__(&self) -> String {
        match &self.name {
            Some(n) => format!("<AsyncUser {n}>"),
            None => "<AsyncUser (current)>".to_owned(),
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::mock::TestHarness;
    use crate::command::RawOutput;

    #[test]
    fn test_getent_field_home() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"testuser:x:1000:1000:Test User:/home/testuser:/bin/bash\n".to_vec(),
            stderr: vec![],
        }]);
        let home = h
            .inner
            .runtime
            .block_on(getent_field(&h.inner, "testuser", 5))
            .unwrap();
        assert_eq!(home, "/home/testuser");
        assert_eq!(
            h.calls(),
            [("getent".into(), vec!["passwd".into(), "testuser".into()])]
        );
    }

    #[test]
    fn test_getent_field_shell() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"testuser:x:1000:1000:Test User:/home/testuser:/bin/zsh\n".to_vec(),
            stderr: vec![],
        }]);
        let shell = h
            .inner
            .runtime
            .block_on(getent_field(&h.inner, "testuser", 6))
            .unwrap();
        assert_eq!(shell, "/bin/zsh");
    }

    #[test]
    fn test_groups_splitting() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"wheel docker users\n".to_vec(),
            stderr: vec![],
        }]);
        let groups = h
            .inner
            .runtime
            .block_on(groups_impl(&h.inner, "testuser"))
            .unwrap();
        assert_eq!(groups, vec!["wheel", "docker", "users"]);
        assert_eq!(
            h.calls(),
            [("id".into(), vec!["-nG".into(), "testuser".into()])]
        );
    }

    #[test]
    fn test_uid_parse() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 0,
            stdout: b"1000\n".to_vec(),
            stderr: vec![],
        }]);
        let uid = h
            .inner
            .runtime
            .block_on(uid_impl(&h.inner, "testuser"))
            .unwrap();
        assert_eq!(uid, 1000);
        assert_eq!(
            h.calls(),
            [("id".into(), vec!["-u".into(), "testuser".into()])]
        );
    }

    #[test]
    fn test_is_declared_true() {
        let h = TestHarness::new(vec![
            RawOutput {
                rc: 0,
                stdout: b"/nix/store/abc123-users-groups.json\n".to_vec(),
                stderr: vec![],
            },
            RawOutput {
                rc: 0,
                stdout: br#"{"users":[{"name":"testuser"},{"name":"root"}],"groups":[],"mutableUsers":true}"#.to_vec(),
                stderr: vec![],
            },
        ]);
        assert!(
            h.inner
                .runtime
                .block_on(is_declared_impl(&h.inner, "testuser"))
                .unwrap()
        );
        assert_eq!(
            h.calls(),
            [
                (
                    "grep".into(),
                    vec![
                        "-oP".into(),
                        r"/nix/store/[a-z0-9]+-users-groups\.json".into(),
                        "/run/current-system/activate".into()
                    ]
                ),
                (
                    "cat".into(),
                    vec!["/nix/store/abc123-users-groups.json".into()]
                )
            ]
        );
    }

    #[test]
    fn test_is_declared_false() {
        let h = TestHarness::new(vec![
            RawOutput {
                rc: 0,
                stdout: b"/nix/store/abc123-users-groups.json\n".to_vec(),
                stderr: vec![],
            },
            RawOutput {
                rc: 0,
                stdout: br#"{"users":[{"name":"root"}],"groups":[],"mutableUsers":true}"#.to_vec(),
                stderr: vec![],
            },
        ]);
        assert!(
            !h.inner
                .runtime
                .block_on(is_declared_impl(&h.inner, "imperative-user"))
                .unwrap()
        );
    }

    #[test]
    fn test_is_declared_no_manifest() {
        let h = TestHarness::new(vec![RawOutput {
            rc: 1,
            stdout: b"".to_vec(),
            stderr: vec![],
        }]);
        assert!(
            !h.inner
                .runtime
                .block_on(is_declared_impl(&h.inner, "anyone"))
                .unwrap()
        );
    }
}
