[book]
authors = ["Sharlon N. Regales"]
language = "en"
src = "src"
title = "oxi-nixinfra Internals"

[build]
build-dir = "book"

[output.html]
site-url = "/oxi-nixinfra/internals/"
git-repository-url = "https://github.com/kalonji-tools/oxi-nixinfra"
edit-url-template = "https://github.com/kalonji-tools/oxi-nixinfra/edit/main/docs/internals/{path}"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.fold]
enable = true
level = 0
